### PR TITLE
Added Roles and Events

### PR DESCRIPTION
**Pull request by ardnaxelarak**
Added roles and events from ITL
also fixed error causing special events not to show

### CODE REVIEW

**Comment by ardnaxelarak** [comment]
Currently the "Retrieve Special Event" option for the Contigency Planner will merely remove it from the discard pile and add it to the player's hand; this means it will be added back to the discard pile when played again instead of being removed from the game, and also that it will allow the Contigency Planner to take another event card from the discard pile before playing the first, which should not be allowed.

**Comment by ardnaxelarak** [comment]
Currently the 2nd Edition base roles (Contigency Planner and Quarantine Specialist) will always be included regardless of expansion, and choosing the In The Lab expansion will also include roles and events from On The Brink.

**Comment by jason17055** [comment]
I haven't tested it, but what I see looks good. How did you generate the new image files? (Did you notice there are vector file sources in the toplevel orig_images subdirectory?)

**Comment by ardnaxelarak** [comment]
I pulled them from the rulebook pdfs. Frustratingly, they are inconsistently sized...
I did not see the vector file sources--from that I think I could bring over the colors used in the image in the rulebook to your icons, which looked nicer than the ones straight from the rulebook.

**Comment by ardnaxelarak** [comment]
It looks like the icons you had have more contrast in color than the ones I got from the rulebook--it might do well to tweak them a bit to improve the contrast between the lighter and darker parts, but in any case they certainly look better now than the icons I had previously had.
I added in the Bioterrorist just in case we'd want it in the future since it wasn't much extra work given what I was already doing, but in retrospect I don't see any possible use we could have for it since the bioterrorist introduces enough changes in which infection cards will be drawn by the players that I don't see much point in including it as an option.

**Pull request merged**
